apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/kubedata
    server: 192.168.1.190
