kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-elastic-graylog-elasticsearch-master-0
  namespace: graylog
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
