kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-graylog
  namespace: graylog
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
